### ISSUE TITLE
Question: Release time schedule

### ISSUE THREAD

**Issue by martinjaeger** [okrasolar/okra-bootloader#2]
Very happy to see that you are planning to release also your bootloader as open source, as we are currently starting to implement one for the Libre Solar charge controllers (also using STM32 MCUs).

Do you have a time estimate when you are planning to push the code?

Thanks!
Martin

**Comment by martinjaeger** [comment]
Ah, just realized there is an "initial" branch already. I will have a look :)

**Comment by lippit** [comment]
Hey,
the initial code should already work, I successfully tried to boot a binary with it. There will be ongoing work in the next days.

**Comment by martinjaeger** [comment]
Closing this as the bootloader has been merged to master.
