### ISSUE TITLE
Meson build error

### ISSUE THREAD

**Issue by azeemshatp** [okrasolar/okra-bootloader#3]
Hi
meson build gives me the below error in windows 10. Any advice?

meson.build:1:0: ERROR: Unknown compiler(s): ['icl', 'cl', 'cc', 'gcc', 'clang', 'clang-cl', 'pgcc']
The follow exceptions were encountered:
Running "icl " gave "[WinError 2] The system cannot find the file specified"
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "cc --version" gave "[WinError 2] The system cannot find the file specified"
Running "gcc --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang-cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "pgcc --version" gave "[WinError 2] The system cannot find the file specified"

**Comment by lippit** [comment]
Hey,
do you have the ARM GCC compiler installed? It's available here:
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

In case you want to use a different compiler, you can edit the binaries-section of the meson.cross.build file accordingly.

**Comment by azeemshatp** [comment]
Yes, I did that already and had also added the path to system variables. Do I have to change the below in meson.cross.build in Windows?
mcu_src_dir = './bootloader'

**Comment by NithyaMenon** [comment]
@azeemshatp sorry about the delay in getting back to you! I had the same issues on Windows initially. You will also need to install MinGW which will give you native access to the compilers. 
Let me know if you have any other issues!

**Comment by azeemshatp** [comment]
Hi
Thanks for the reply, and I will try this. I was able to configure PlatformIO with mbed to build, however, the generated binary was around 17K, in contrast to the 800 bytes as you mentioned. Do you think this can be solved using meson+ninja build?

**Comment by NithyaMenon** [comment]
@azeemshatp yep, the meson+ninja build, on windows, is ~800 bytes too.

**Comment by azeemshatp** [comment]
Thanks for your inputs. The codes works fine now. Sorry for the delay in updating here.
